---
pipeline:
  build:
    group: build
    image: theasp/openwrt-builder
    commands:
      - ./build.sh

  notify:
    image: drillster/drone-email
    host: 192.168.0.2
    from: drone
    recipients: [ theasp@gmail.com ]
    when:
      status: [ changed, failure ]
